version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-todo-app
    overwrite: true
file_exists_behavior: OVERWRITE
# permissions:
#   - object: /home/ubuntu/aws-todo-app/scripts
#     pattern: "*.sh"
#     owner: ubuntu
#     group: ubuntu
#     mode: 755
#     type:
#       - file
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

